name: Docker Hub Deploy

on:
  repository_dispatch:
    types: [docker_hub] # github.event.client_payload.original_version

  workflow_dispatch:
    inputs:
      original_version:
        description: "Original CNCjs version"
        required: true
        default: "v1.10.3"

      process_id:
        description: "Process ID"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: parameters
        shell: bash
        run: |
          if [ '${{ github.event_name }}' = 'repository_dispatch' ]; then
            echo "original_version=${{ github.event.client_payload.original_version }}" >> $GITHUB_OUTPUT
            echo "process_id=${{ github.event.client_payload.process_id }}" >> $GITHUB_OUTPUT
          else
            echo "original_version=${{ github.event.inputs.original_version }}" >> $GITHUB_OUTPUT
            echo "process_id=${{ github.event.inputs.process_id }}" >> $GITHUB_OUTPUT
          fi
          echo "step=docker_hub" >> $GITHUB_OUTPUT

      - name: Start CI Log
        run: |
          curl --location '${{ vars.FB_FUNCTION_URL }}' \
            --header 'x-connection-id: ${{ secrets.FB_CON_ID }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "version": "${{ steps.parameters.outputs.original_version }}",
              "step": "${{ steps.parameters.outputs.step }}",
              "start": true,
              "processId": "${{ steps.parameters.outputs.process_id }}",
              "runId": ${{ github.run_id }},
              "runStatus": "in_progress",
              "runConclusion": "initial"
            }'

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mxpicture
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/*/})"
        if: ${{ (github.event_name != 'repository_dispatch') && (github.event_name != 'workflow_dispatch') }}
        id: extract_tag

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          # platforms: linux/amd64,linux/arm64,linux/arm
          platforms: linux/arm64
          tags: mxpicture/cncjs:${{ steps.parameters.outputs.original_version }},mxpicture/cncjs:latest
          build-args: "BASE_IMAGE_VERSION=${{ steps.parameters.outputs.original_version }}"

      - name: Stop CI Log
        run: |
          curl --location '${{ vars.FB_FUNCTION_URL }}' \
            --header 'x-connection-id: ${{ secrets.FB_CON_ID }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "version": "${{ steps.parameters.outputs.original_version }}",
              "step": "${{ steps.parameters.outputs.step }}",
              "start": false,
              "processId": "${{ steps.parameters.outputs.process_id }}",
              "runId": ${{ github.run_id }},
              "runStatus": "completed",
              "runConclusion": "success"
            }'
