name: Docker Hub Deploy

on:
  push:
    tags: ["*"]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mxpicture
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/*/})"
        if: github.event_name != 'repository_dispatch'
        id: extract_tag

      - name: Build and push (on push)
        id: docker_build_push
        uses: docker/build-push-action@v4
        if: github.event_name != 'repository_dispatch'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: mxpicture/cncjs:${{ steps.extract_tag.outputs.tag }},mxpicture/cncjs:latest
          build-args: "BASE_IMAGE_VERSION=${{ steps.extract_tag.outputs.tag }}"

      - name: Build and push (on dispatch)
        id: docker_build_dispatch
        uses: docker/build-push-action@v4
        if: github.event_name == 'repository_dispatch'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: mxpicture/cncjs:${{ github.event.client_payload.tag }}
          build-args: "BASE_IMAGE_VERSION=${{ github.event.client_payload.tag }}"
